# General
spring.application.name=picas-fijas

# Database (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d81joppj2pic73fp66g0-a.oregon-postgres.render.com:5432/picas_fijas?ssl=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rafael}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:GB2SYaTKNjbWEC67z3QNu7jdv2911j48}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# Content-Type
spring.mvc.converters.preferred-json-mapper=jackson
